---
- name: Playbook que instala agente
  become: true
  hosts: all
  tasks:
   - name: Descarga agente
     shell: 'wget  -O Dynatrace-OneAgent-Linux-1.331.49.20260227-104933.sh "https://bht57484.live.dynatrace.com/api/v1/deployment/installer/agent/unix/default/latest?arch=x86" --header="Authorization: Api-Token {{token}}"'

   - name: Instala agente
     shell: 'sudo /bin/sh Dynatrace-OneAgent-Linux-1.331.49.20260227-104933.sh --set-monitoring-mode=fullstack --set-app-log-content-access=true'
