---
- name: Playbook que limpia disco lleno
  become: true
  hosts: all
  tasks:
   - name: Crea directorio
     file:
       path: /home/ec2-user/discolleno
       state: directory
   - name: Info del disco
     shell: "df -h /home/ec2-user/discolleno"
   - name: Limpia disco
     shell: "rm -rf /home/ec2-user/discolleno/*"
