---
- name: Playbook que limpia disco lleno
  become: true
  hosts: all
  tasks:
   - name: Crea directorio
     file:
       path:  /tmp/backup
       state: directory
   - name: Info del disco
     shell: "df -h  /tmp/backup"
   - name: Limpia disco
     shell: "rm -rf  /tmp/backup/*"
