---
- name: Playbook que configura el cliente nfs
  become: true
  hosts: all
  tasks:
   - name: Instala nfs-utils
     yum:
       name:  nfs-utils
       state: latest
   - name:
     file:
       path: /tmp/backup/
       state: directory
       mode: "0755"
   - name: Monta el nfs
     mount:
       src: node2:/mnt/datos/
       path: /tmp/backup
       fstype: nfs
       state: mounted
       opts: "defaults,_netdev"
